[build]
  publish = "."
  command = "cd backend && npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/ONE2.HTML"
  status = 200
